version: 0.2

phases:
  build:
    commands:
    - ARCH="$([ "x86_64" = "$(uname -m)" ] && echo amd64 || echo arm64)"
    - ./_bin/$ARCH/e2e-test sweeper --cluster-prefix "nodeadm-e2e-tests-" --eks-endpoint "${EKS_ENDPOINT:-}"
